name: NPM Test

on:
  push:
    paths:
      - "src/**"
      - "test/**"
  workflow_dispatch:

jobs:
  npm-test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        shell: bash
      - run: npm test --if-present
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 14
          - 16
