name: NPM Test

on:
  push:
    paths:
      - "src/**"
      - "test/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  npm-test:
    uses: nujarum/actions/.github/workflows/npm-test.yml@main
