name: Publish Package

on:
  release:
    types:
      - created

jobs:
  npm-test:
    uses: nujarum/actions/.github/workflows/npm-test.yml@main
  npm-publish:
    needs: npm-test
    uses: nujarum/actions/.github/workflows/npm-publish.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      scope: "@nujarum"
